// Create a custom Cloud9 runner - similar to the Sublime build system
// For more information see http://docs.aws.amazon.com/console/cloud9/create-run-config
{
    "info" : "Synthesizing with Quartus ... $project_path$file_name",
    "script": [
      // set Quartus environment
      "export QUARTUS_ROOTDIR=/home/ubuntu/intelFPGA_lite/22.1std/quartus/",
      "export PATH=$PATH:$QUARTUS_ROOTDIR/bin",

      // set to exit if any non-zero returned
      "set -e",
      "quartus_sh --flow compile $file_base_name",
      "quartus_cpf  -c -q 1MHz -g 3.3 -n p output_files/$file_base_name.sof output_files/$file_base_name.svf",
      "quartus_cpf  -c -q 1MHz -g 3.3 -n p output_files/$file_base_name.sof output_files/$file_base_name.p.svf",
      // clean up vcd files
      "rm -rf *.vcd *.lxt2"
    ],
    "env" : {},
    // select any *.qsf extension
    "selector": "^.*\\.(qsf)$"
}
